name: create-png
run-name: Creating PNG from SVG
on:
  push:
    paths:
      FAQ.svg
      
jobs:
  create-png:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout repo'
        uses: actions/checkout@v4

      - name: 'Install nix'
        uses: DeterminateSystems/nix-installer-action@v9
      
      - name: 'Create PNG'
        if: steps.restore-nix-store.outputs.cache-hit != 'true'
        run: |
          nix-shell -p firefox --command "firefox -screenshot file://\$(realpath FAQ.svg) --window-size 1280,720"
          mv screenshot.png FAQ.png
          
      - name: 'Upload PNG Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: FAQpng
          path: ./FAQ.png
          retention-days: 5
