name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  create-png:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout repo'
        uses: actions/checkout@v4

      - name: 'Install nix'
        uses: DeterminateSystems/nix-installer-action@v9
      
      - name: 'Create PNG'
        run: nix-shell -p firefox --command "firefox -screenshot file://\$(realpath FAQ.svg) --window-size 1280,720"

      - name: 'Upload PNG Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: FAQpng
          path: ./screenshot.png
          retention-days: 5

      - name: 'Cache Firefox'
        uses: actions/cache@v4.2.3
        with:
          path: /nix/store
