name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  create-png:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout repo'
      - uses: actions/checkout@v4
      
      - name: 'Create PNG'
      - run: |
          apt install firefox
          firefox -headless -screenshot file://$(realpath FAQ.svg)

      - name: 'Upload Artifact'
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./screenshot.png
          retention-days: 5
